accepted = [
	"BSL-1.0",
    "MIT",
    "Apache-2.0",
	"MPL-2.0",
	"Unicode-DFS-2016",
]
targets = [
	"x86_64-unknown-none",
]
ignore-build-dependencies = true
ignore-dev-dependencies = true
ignore-transitive-dependencies = false
