[workspace]

members = [
    "kernel",
    "display-daemon"
]
resolver = "2"

[workspace.package]
authors = ["Caleb Baker <calebbaker774@gmail.com"]
license-file = "LICENSE"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

