[package]
name = "display-daemon"
version = "0.1.0"
authors = ["CalebLBaker <calebbaker774@gmail.com>"]
edition = "2021"

[lib]
path = "src/arch/amd64/lib.rs"

[dependencies]
volatile = "^0.5"
spin = "^0.9"
[dependencies.lazy_static]
version = "^1.4"
features = ["spin_no_std"]

