[package]
name = "micros_memory_manager"
version = "0.2.2"
edition = "2024"
authors = ["Caleb Baker <calebbaker774@gmail.com>"]
license = "BSL-1.0"

[dependencies]
frame_allocation = { path = "../frame_allocation" }
multiboot2 = { path = "../multiboot2" }
framebuffer = { path = "../framebuffer" }
address = { path = "../address" }
architecture = { path = "../architecture" }
