[package]
name = "micros_memory_manager"
version = "0.2.1"
edition = "2021"
authors = ["Caleb Baker <calebbaker774@gmail.com>"]
license = "BSL-1.0"

[dependencies]
frame_allocation = { path = "../frame_allocation" }
multiboot2 = { path = "../multiboot2" }
framebuffer = { path = "../framebuffer" }
