[package]
name = "micros_memory_manager"
version = "0.1.0"
edition = "2021"
authors = ["Caleb Baker <calebbaker774@gmail.com>"]
license = "BSL-1.0"

[dependencies]
frame_allocation = { path = "../frame_allocation" }
micros_console_writer = { path = "../micros_console_writer" }
