[package]
name = "micros_console_writer"
version = "0.1.0"
edition = "2021"
authors = ["Caleb Baker <calebbaker774@gmail.com>"]
license = "BSL-1.0"

[dependencies]
volatile = "^0.5"
spin = "^0.9"
[dependencies.lazy_static]
version = "^1.4"
features = ["spin_no_std"]

