[package]
name = "micros_kernel_common"
version = "0.1.0"
authors = ["CalebLBaker <calebbaker774@gmail.com>"]
license = "BSL-1.0"
edition = "2021"

[dependencies]
multiboot2 = { version = "0.19.0", default-features = false }
